### ISSUE TITLE
Bug: API docs generation is incomplete

### ISSUE THREAD

**Issue by jim-parry** [codeigniter4/CodeIgniter4#1988]
The [phpDocumentor2](http://www.phpdoc.org/) tool used to generate our API docs does not properly recognize all PHP7 syntax. The source scanning flags the source code as having a syntax error, and the class is not included in the API docs. This is expected to be addressed in phpDocumentor3, which is in alpha.3. I will monitor the tool, and close this once we have resolution, but wanted to document the problem in the meantime.

The syntax errors, and affected API doc classes are shown below.

PHP7 allows [previously reserved words to be used as method names](https://www.php.net/manual/en/reserved.keywords.php).
- CLI/CLI (unexpected T_PRINT, expecting T_STRING on line 307)
- View/Filters (unexpected T_DEFAULT, expecting T_STRING on line 113)
- View/View (unexpected T_INCLUDE, expecting T_STRING on line 499)

PHP7 provides type hinting, which messes up parsing of some of our source.
- Files/File (unexpected '?' on line 121)
- Helpers/number_helper (unexpected '?' on line 270)
- HTTP/FIles/UploadedFile (unexpected '?' on line 359)
- I18n/Time (unexpected '?', expecting T_VARIABLE on line 1039)
- Test/CUUnitTestCase (unexpected '?' on line 253)

PHP7 provides for array declarations on the left side of an assignment, sorta like the [list construct](https://www.php.net/manual/en/function.list.php), which has caused some parsing hiccups.
- Router/Router (unexpected '=' on line 472)
- Language/Language (unexpected '=' on line 149)

**EDIT: It sounds like version 3.0.0 of the tool will solve many (all?) of the issues**

**Comment by jim-parry** [comment]
Just an update: still waiting for phpDocumentor 3, to properly handle PHP7 syntax

**Comment by rajat315315** [comment]
phpDocumentor 2.9 is out there. I think maybe someone can try that to see if it solves.

**Comment by MGatner** [comment]
@rajat315315 Unfortunately Jim passed away earlier this year. https://forum.codeigniter.com/thread-75235.html

I have no experience with phpDocumentor, but we did add a workflow to generate docs automatically: https://github.com/codeigniter4/CodeIgniter4/blob/develop/.github/workflows/apidocs-action.yml

Do you feel the issue is resolved?

**Comment by paulbalandan** [comment]
The action workflow is currently using version 2.9. When I developed that, the same errors are still showing. I have tried using the early releases of version 3 before and it thankfully got rid of the parse errors. Unfortunately, v3's dependencies are the ones causing errors now as they have code incompatible with PHP7.4

**Comment by MGatner** [comment]
@paulbalandan I expect the version 3 kinks have been worked out by now. Any chance you could run through whatever you did nine months ago and see if we are ready to make this leap?

**Comment by paulbalandan** [comment]
Actually there is and v3 has a change in the config file. I have looked into this before. I'll take on this in the following days.
